// Generated by https://quicktype.io

export interface Data {
  parties: Parties;
  _id: string;
  state: string;
  city: string;
  dateTime: Date;
  budget: number;
  status: string;
  package: string;
  role: string;
  createdAt: Date;
  __v: number;
}

export interface Parties {
  senderId: string;
  receiverId: string;
}

export interface QueryData {
  package: Package;
  _id: string;
  userId: string;
  firstName: string;
  lastName: string;
  rating: number;
  events: { [key: string]: Event };
  state: string;
  city: string;
  verified: boolean;
  balance: number;
  role: string;
  clients: any[];
  responseTimes: number[];
  ratings: any[];
  selections: any[];
  samples: any[];
  createdAt: Date;
  __v: number;
  currentlyHiredBy?: boolean;
  business: Business;
  gender: string;
  identityVerify: IdentityVerify;
  phoneNumber: string;
  company: Company;
  publicId: string;
  picture: string;
  averageResponseTime: number;
}

export interface Business {
  officeAddress: string;
  _id: string;
}

export interface Company {
  description: string;
  image: string;
  name: string;
  _id: string;
}

export interface Event {
  status: string;
  bookedOn: Date;
  declined: boolean;
  declinedReason: null;
  _id: string;
}

export interface IdentityVerify {
  _id: string;
}

export interface Package {
  standard: Basic;
  basic: Basic;
  premium: Basic;
}

export interface Basic {
  service: string[];
  price: number;
}
